"""initial schema (spec section 6)

Revision ID: bff5ab3a2afb
Revises: 
Create Date: 2026-06-10 13:33:47.724923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff5ab3a2afb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_questions', schema=None) as batch_op:
        batch_op.create_index('idx_date', ['scheduled_date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=False),
    sa.Column('social_provider', sa.Enum('kakao', 'apple', 'dev', name='social_provider'), nullable=False),
    sa.Column('social_id', sa.String(length=128), nullable=False),
    sa.Column('relationship_status', sa.Enum('couple', 'single', 'married', name='relationship_status'), nullable=False),
    sa.Column('couple_id', sa.BigInteger(), nullable=True),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_social', ['social_provider', 'social_id'], unique=False)

    op.create_table('blocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('blocked_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'blocked_user_id', name='uq_block')
    )
    op.create_table('couples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_a', sa.BigInteger(), nullable=False),
    sa.Column('user_b', sa.BigInteger(), nullable=True),
    sa.Column('invite_code', sa.String(length=6), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('daily_answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('couple_id', sa.BigInteger(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['daily_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'user_id', name='uq_answer')
    )
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('love', 'marriage', 'counsel', 'free', name='post_category'), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_poll', sa.Boolean(), nullable=False),
    sa.Column('author_status', sa.Enum('couple', 'single', 'married', name='author_status_post'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('hot_score', sa.Float(), nullable=False),
    sa.Column('is_blinded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('idx_cat_created', ['category', 'created_at'], unique=False)
        batch_op.create_index('idx_hot', [sa.literal_column('hot_score DESC')], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('target_type', sa.Enum('post', 'comment', 'user', name='report_target'), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('author_status', sa.Enum('couple', 'single', 'married', name='author_status_comment'), nullable=False),
    sa.Column('is_blinded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_post', ['post_id', 'created_at'], unique=False)

    op.create_table('poll_options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.Enum('A', 'B', name='poll_side'), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('couple_id', sa.BigInteger(), nullable=False),
    sa.Column('owner', sa.Enum('a', 'b', 'both', name='schedule_owner'), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index('idx_couple_date', ['couple_id', 'event_date'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('option_side', sa.Enum('A', 'B', name='vote_side'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_vote')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index('idx_couple_date')

    op.drop_table('schedules')
    op.drop_table('poll_options')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index('idx_post')

    op.drop_table('comments')
    op.drop_table('reports')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_hot')
        batch_op.drop_index('idx_cat_created')

    op.drop_table('posts')
    op.drop_table('daily_answers')
    op.drop_table('couples')
    op.drop_table('blocks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_social')

    op.drop_table('users')
    with op.batch_alter_table('daily_questions', schema=None) as batch_op:
        batch_op.drop_index('idx_date')

    op.drop_table('daily_questions')
    # ### end Alembic commands ###
